### PR TITLE
Ref: Changed line 42 from to_json to to_s 

### PR DESCRIPTION
**Pull request by charlesagyemang**

### CODE REVIEW

**Comment by EDDYMENS** [comment]
@charlesagyemang thanks for the PR, Can you please attach an explanation for the change from JSON output to string.

**Comment by charlesagyemang** [comment]
## Reason:
 String is easy to convert to any form, giving them default json kinda restricts them. They will have to covert Json to string id that is not what they need and it will have all the back slashes but the string will be clean and its easy to cover to son but either way the two methods will be ok solar as it work string is just my preference I work easier with them

**Comment by EDDYMENS** [comment]
@charlesagyemang can we have the description in the comment box. lol

**Comment by EDDYMENS** [comment]
@paynegreen please confirm the merge

**Pull request merged**
