### PR TITLE
Kwaku

### PR DESCRIPTION
**Pull request by bkwaku**
Search is now ready to be used in the ruby SDK.

### CODE REVIEW

**Comment by EDDYMENS** [comment]
@bkwaku good one with the addition of the search query param. A note though, seems you edited the SDK  example code  `specifically the SDK require path`.

**Comment by EDDYMENS** [comment]
@paynegreen confirm the changes for final merge

**Comment by bkwaku** [comment]
Can we put the `SDK example code` in the .gitignore file so we don't keep editing and undoing the changes in that file.

**Comment by EDDYMENS** [comment]
@bkwaku it forms part of the package and serves as a reference point. If you feel a need to edit it create a copy for while you work. Once you are ready to send a PR  don't commit your copy , just your changes

**Comment by bkwaku** [comment]
Alright cool!

**Comment by paynegreen** [comment]
@bkwaku there's a merge conflict with the request processor method. Please review your implementation and submit a pull request again.

**Comment by bkwaku** [comment]
Conflicts resloved!

**Pull request merged**
