### PR TITLE
Bug: Fixed the error on line 43.

### PR DESCRIPTION
**Pull request by charlesagyemang**
Fixed the error it threw whenever a response was being. It crashed because it was being rendered "to_h" instead of "to_s" to maybe "to_json". Its working now I change it to "to_json". Please review and make changes. I salute you guys.

### CODE REVIEW

**Comment by EDDYMENS** [comment]
Nice catch 👍  thanks for the fix. Would you like to improve the README too ? :1st_place_medal:   for you. 😉

**Comment by charlesagyemang** [comment]
Thanks chief I would love to help out with the read as well. Thanks for the opportunity. I am on it as we speak.

**Comment by EDDYMENS** [comment]
Great!! Will love for us to talk, feel free to pass by the office or we can plan to meet somewhere else?

**Comment by charlesagyemang** [comment]
Cool I will do that. I send another pull request> Added an example folder to walk people through the process in with rails and normal ruby script yh. Look at that too. We will meet. Thanks chief

**Comment by EDDYMENS** [comment]
👍

**Comment by charlesagyemang** [comment]
:thumbsup:

**Pull request merged**
